In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
from scipy import stats
from warnings import filterwarnings
filterwarnings('ignore')

In [4]:
df = pd.read_csv('/content/drive/MyDrive/sample_with_duplicates.csv')
df.head()

,id,name,age,salary,joining date,is Active,commnts,name_duplicate,salary_duplicate
0,1,Ali Khan,28.0,NaN,2021-03-15,True,Excellent performance,Ali Khan,NaN
1,2,Sara Malik,NaN,67000.0,NaN,NaN,NaN,Sara Malik,67000.0
2,3,Umar Farooq,41.0,73000.0,NaN,False,Left the company,Umar Farooq,73000.0
3,4,NaN,26.0,NaN,2022-01-10,True,New hire,NaN,NaN
4,5,Tariq Javed,37.0,62000.0,2020-05-30,NaN,Needs improvement,Tariq Javed,62000.0

In [5]:
df['name'].fillna('Unknown', inplace=True)
df['age']=df['age'].fillna(df['age'].mean())
df['salary']=df['salary'].fillna(df['salary'].mode()[0])
df['joining date']=pd.to_datetime(df['joining date'])
df['joining date']=df['joining date'].fillna(df['joining date'].median())
df['is Active']=df['is Active'].fillna(df['is Active'].mode()[0])
df['commnts']=df['commnts'].fillna(df['commnts'].mode()[0])
df.drop_duplicates(inplace=True)
# df.drop(["name_duplicate", "salary_duplicate"], axis=1, inplace=True)
df.head()

,id,name,age,salary,joining date,is Active,commnts,name_duplicate,salary_duplicate
0,1,Ali Khan,28.0,73000.0,2021-03-15,True,Excellent performance,Ali Khan,NaN
1,2,Sara Malik,34.1,67000.0,2021-03-15,True,Excellent performance,Sara Malik,67000.0
2,3,Umar Farooq,41.0,73000.0,2021-03-15,False,Left the company,Umar Farooq,73000.0
3,4,Unknown,26.0,73000.0,2022-01-10,True,New hire,NaN,NaN
4,5,Tariq Javed,37.0,62000.0,2020-05-30,True,Needs improvement,Tariq Javed,62000.0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['name'] = le.fit_transform(df['name'])
df['commnts']=le.fit_transform(df['commnts'])

df.head()

In [ ]:
dfcleaned=pd.get_dummies(df,columns=['is Active'])

dfcleaned.head()

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
dfcleaned['joining date']=scaler.fit_transform(dfcleaned[['joining date']])
dfcleaned.head()

,id,name,age,salary,joining date,commnts,name_duplicate,salary_duplicate,is Active_False,is Active_True
0,1,0,28.0,73000.0,0.749374,0,Ali Khan,NaN,False,True
1,2,4,34.1,67000.0,0.749374,0,Sara Malik,67000.0,False,True
2,3,6,41.0,73000.0,0.749374,1,Umar Farooq,73000.0,True,False
3,4,7,26.0,73000.0,0.856990,3,NaN,NaN,False,True
4,5,5,37.0,62000.0,0.646049,2,Tariq Javed,62000.0,False,True

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/train (1).csv')
df.head()
# df.isnull().sum()

In [ ]:
df.dtypes

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())
# df.drop('Cabin',axis=1,inplace=True)
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])
df.isnull().sum()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Name']=le.fit_transform(df['Name'])
df['Sex']=le.fit_transform(df['Sex'])
df['Ticket']=le.fit_transform(df['Ticket'])
df['Embarked']=le.fit_transform(df['Embarked'])
df['Fare']=le.fit_transform(df['Fare'])
df.head()

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df['Age']=scaler.fit_transform(df[['Age']])
df['Fare']=scaler.fit_transform(df[['Fare']])
df['Ticket']=scaler.fit_transform(df[['Ticket']])
df.head()

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/car_evaluation.csv')
df.head()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
# df['vhigh']=le.fit_transform(df['vhigh'])
# df['vhigh.1']=le.fit_transform(df['vhigh.1'])
# df['2']=le.fit_transform(df['2'])
# df['2.1']=le.fit_transform(df['2.1'])
# df['small']=le.fit_transform(df['small'])
# df['low']=le.fit_transform(df['low'])
# df['unacc']=le.fit_transform(df['unacc'])
# df.head(19)
LabelEncoder={}
for col in df.columns:
  df[col]=le.fit_transform(df[col])
print(LabelEncoder)
df.head()

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/WineQT.csv')
df.head()