In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import pandas as pd

In [4]:
df =pd.read_csv('/content/drive/MyDrive/sample_with_missing_values.csv')
# df.shape
df.head(6)
# print (df.dtypes)

,id,name,age,salary,joining date,is Active,commnts
0,1,Ali Khan,28.0,NaN,2021-03-15,True,Excellent performance
1,2,Sara Malik,NaN,67000.0,NaN,NaN,NaN
2,3,Umar Farooq,41.0,73000.0,NaN,False,Left the company
3,4,NaN,26.0,NaN,2022-01-10,True,New hire
4,5,Tariq Javed,37.0,62000.0,2020-05-30,NaN,Needs improvement
5,6,Mahnoor Raza,29.0,58000.0,2021-08-17,False,On extended leave

In [ ]:
df.isnull().sum()

In [ ]:
df['name'].fillna("Unknown", inplace = True)
df['age']=df['age'].fillna(df['age'].mean())
df['salary']=df['salary'].fillna(df['salary'].mean())
df['joining date'] = pd.to_datetime(df['joining date'])
df['joining date']=df['joining date'].fillna(df['joining date'].median())
df['is Active'] = df['is Active'].fillna(df['is Active'].mode()[0])
df['commnts'] = df['commnts'].fillna(df['commnts'].mode()[0])


df.head(9)

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/train (1).csv')
df.head(10)

In [ ]:
df.isnull().sum()

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())
# Step 2: Fill missing values in 'Cabin' with 'Unknown'
df['Cabin'].fillna('Unknown', inplace=True)

# Step 3: Extract deck letter (first character of cabin value or 'U' for unknown)
df['Deck'] = df['Cabin'].apply(lambda x: x[0] if x != 'Unknown' else 'U')

# Step 4: Optional – See value counts of each Deck

df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])
df.head()
# df.isnull().sum()

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/WineQT.csv')
df.shape
df.head(20)

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/car_evaluation.csv')
# df.shape
# df.isnull().sum()
df.head(20)

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/car_evaluation_sample_200.csv')
df.head(10)