In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import pandas as pd

In [ ]:
df =pd.read_csv('/content/drive/MyDrive/customers-100.zip')

In [ ]:
df.shape

(100, 12)

In [ ]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,NaN,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,NaN,West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [ ]:
df.isnull().sum()

Index                 0
Customer Id           0
First Name            0
Last Name             0
Company               2
City                 13
Country               0
Phone 1               9
Phone 2               0
Email                 0
Subscription Date     0
Website               0
dtype: int64

In [6]:
data = {
    'Name': ['Ali', 'Sara', 'Zain', 'Hina', 'Ahmed', 'Rida', 'Usman', 'Fatima', 'Bilal', 'Ayesha',
             'Kashif', 'Laiba', 'Tariq', 'Nida', 'Fahad', 'Mina', 'Saad', 'Anum', 'Arif', 'Sana'],

    'Age': [25, 22, None, 28, 30, None, 24, 27, None, 23,
            29, None, 31, 26, None, 21, 33, None, 32, None],

    'Salary': [50000, 55000, None, 60000, None, 52000, 58000, None, 61000, None,
               53000, 57000, None, None, 59000, 54000, None, 56000, None, 62000],

    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female',
               'Male', 'Female', 'Male', 'Female', 'Male', None, 'Male', None, 'Male', None],

    'Joining Date': ['2022-01-10', '2021-05-15', None, '2020-08-20', '2023-03-12', None, '2019-11-01',
                     '2022-06-18', None, '2021-09-07', '2020-02-22', None, '2018-12-30', '2022-04-10',
                     None, '2023-01-25', '2017-07-05', None, '2016-10-19', None],

    'Comments': ['Hardworking', None, 'Needs improvement', 'Excellent team player', None, 'Quick learner',
                 'Consistent', None, 'On probation', None, 'Punctual', None, 'Senior staff', 'Good communication',
                 None, 'New joiner', 'Promoted recently', None, 'Technical expert', None],

    'Active Status': [True, True, None, True, False, True, None, True, False, None,
                      True, False, None, True, None, True, True, None, False, None]
}

df=pd.DataFrame(data)
print (df)

      Name   Age   Salary  Gender Joining Date               Comments  \
0      Ali  25.0  50000.0    Male   2022-01-10            Hardworking
1     Sara  22.0  55000.0  Female   2021-05-15                   None
2     Zain   NaN      NaN    Male         None      Needs improvement
3     Hina  28.0  60000.0  Female   2020-08-20  Excellent team player
4    Ahmed  30.0      NaN    Male   2023-03-12                   None
5     Rida   NaN  52000.0  Female         None          Quick learner
6    Usman  24.0  58000.0    Male   2019-11-01             Consistent
7   Fatima  27.0      NaN  Female   2022-06-18                   None
8    Bilal   NaN  61000.0    Male         None           On probation
9   Ayesha  23.0      NaN  Female   2021-09-07                   None
10  Kashif  29.0  53000.0    Male   2020-02-22               Punctual
11   Laiba   NaN  57000.0  Female         None                   None
12   Tariq  31.0      NaN    Male   2018-12-30           Senior staff
13    Nida  26.0      NaN  Female   2022-04-10     Good communication
14   Fahad   NaN  59000.0    Male         None                   None
15    Mina  21.0  54000.0    None   2023-01-25             New joiner
16    Saad  33.0      NaN    Male   2017-07-05      Promoted recently
17    Anum   NaN  56000.0    None         None                   None
18    Arif  32.0      NaN    Male   2016-10-19       Technical expert
19    Sana   NaN  62000.0    None         None                   None

   Active Status
0           True
1           True
2           None
3           True
4          False
5           True
6           None
7           True
8          False
9           None
10          True
11         False
12          None
13          True
14          None
15          True
16          True
17          None
18         False
19          None

In [200]:
df['Age']=df['Age'].fillna(df['Age'].median())
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df['Gender']=df['Gender'].fillna(df['Gender'].mode())
df['Joining Date']=df['Joining Date'].fillna(df['Joining Date'].min)
df['Comments']=df['Comments'].fillna("info not updated yet")
df['Active Status']=df['Active Status'].fillna(df['Active Status'].mode()[0])

<ipython-input-200-6c51a7f62a42>:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Active Status']=df['Active Status'].fillna(df['Active Status'].mode()[0])

In [201]:
df.head(10)

,Name,Age,Salary,Gender,Joining Date,Comments,Active Status
0,Ali,25.0,50000.0,Male,2022-01-10,Hardworking,True
1,Sara,22.0,55000.0,Female,2021-05-15,info not updated yet,True
2,Zain,27.0,56500.0,Male,<bound method Series.min of 0 2022-01-10\n...,Needs improvement,True
3,Hina,28.0,60000.0,Female,2020-08-20,Excellent team player,True
4,Ahmed,30.0,56500.0,Male,2023-03-12,info not updated yet,False
5,Rida,27.0,52000.0,Female,<bound method Series.min of 0 2022-01-10\n...,Quick learner,True
6,Usman,24.0,58000.0,Male,2019-11-01,Consistent,True
7,Fatima,27.0,56500.0,Female,2022-06-18,info not updated yet,True
8,Bilal,27.0,61000.0,Male,<bound method Series.min of 0 2022-01-10\n...,On probation,False
9,Ayesha,23.0,56500.0,Female,2021-09-07,info not updated yet,True

In [202]:
from sklearn.preprocessing import LabelEncoder

In [203]:
le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Active Status']=le.fit_transform(df['Active Status'])

In [204]:
df.head()

,Name,Age,Salary,Gender,Joining Date,Comments,Active Status
0,Ali,25.0,50000.0,1,2022-01-10,Hardworking,1
1,Sara,22.0,55000.0,0,2021-05-15,info not updated yet,1
2,Zain,27.0,56500.0,1,<bound method Series.min of 0 2022-01-10\n...,Needs improvement,1
3,Hina,28.0,60000.0,0,2020-08-20,Excellent team player,1
4,Ahmed,30.0,56500.0,1,2023-03-12,info not updated yet,0

In [205]:
onehot=pd.get_dummies(df['Gender'])
print(onehot)

        0      1      2
0   False   True  False
1    True  False  False
2   False   True  False
3    True  False  False
4   False   True  False
5    True  False  False
6   False   True  False
7    True  False  False
8   False   True  False
9    True  False  False
10  False   True  False
11   True  False  False
12  False   True  False
13   True  False  False
14  False   True  False
15  False  False   True
16  False   True  False
17  False  False   True
18  False   True  False
19  False  False   True

In [ ]:
import pandas as pd
onehot=pd.get_dummies(df['Gender'])
df=pd.concat([df,onehot],axis=1).drop(columns=['Gender'])
df.to_csv("Cleaned",index=False  )
print("code done")

code done

In [ ]:
import pandas as pd
onehot=pd.get_dummies(df['Active Status'])
df=pd.concat([df,onehot],axis=1).drop(columns=['Active Status'])
df.to_csv("Cleaned",index=False  )
print("code done")
print(onehot)

code done
    False  True
0   False   True
1   False   True
2   False  False
3   False   True
4    True  False
5   False   True
6   False  False
7   False   True
8    True  False
9   False  False
10  False   True
11   True  False
12  False  False
13  False   True
14  False  False
15  False   True
16  False   True
17  False  False
18   True  False
19  False  False